# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17f37b02626bd426bcf740df83866c2ecabf75f42b3398601c2b66aa81081305162c3bd847fb19eb4665daaeea50328f038b30ca91bdc957e7da8de3e5dd3f6b

test:
  secret_key_base: 6f548b2c05554d966f28341fbce396cbdc7ef1ec672ce5dafdf8f7a0ea1765cc2742ba604b67a26d3cb42aa1ec824ace1230ef5a75d4cdb2544dbedf68dda957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
